import Head from "next/head"
import { Header } from "components/Layout/Header"

interface props {
    children: JSX.Element
}

export const Layout: React.FC<props> = ({children}) => {
    return(
        <>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-laptop bg-no-repeat bg-contain text-light-default">
            <Header/>
            {children}
        </main>
        </>
    )
}